# Pipeline deploying the application to the Azure cloud infrastructure.
parameters:
  - name: environment
    displayName: Environment to manage
    type: string
    default: dev
    values:
    - dev
    - all
  - name: dryRun
    type: boolean
    default: false
  - name: action
    type: string
    default: apply
    values:
      - apply
      - destroy

variables:
- template: ../conf/${{ parameters.environment }}/env.yaml

stages:
- stage: DeployApp
  displayName: Deploy the application
  jobs:
  - job: DeployApp
    displayName: Deploy Application
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: AzureCLI@2
      displayName: "Set TF SP variables"
      inputs:
        azureSubscription: ${{ variables.SERVICE_CONNECTION }}
        scriptType: "bash"
        scriptLocation: "inlineScript"
        addSpnToEnvironment: true
        inlineScript: |
          set -e
          export ARM_CLIENT_ID=$servicePrincipalId
          export ARM_CLIENT_SECRET=$servicePrincipalKey
          export ARM_TENANT_ID=$tenantId
          export ARM_SUBSCRIPTION_ID=$(az account show --query id -o tsv)
          echo "##vso[task.setvariable variable=ARM_CLIENT_ID;]$ARM_CLIENT_ID"
          echo "##vso[task.setvariable variable=ARM_CLIENT_SECRET;]$ARM_CLIENT_SECRET"
          echo "##vso[task.setvariable variable=ARM_SUBSCRIPTION_ID;]${ARM_SUBSCRIPTION_ID}"
          echo "##vso[task.setvariable variable=ARM_TENANT_ID;]$ARM_TENANT_ID"
    - task: JasonBJohnson.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@1
      displayName: "Install Terraform"
      inputs:
        terraformVersion: "latest"
    - task: AzureCLI@2
      displayName: TF Init
      inputs:
        azureSubscription: ${{ variables.SERVICE_CONNECTION }}
        addSpnToEnvironment: true
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          set -xe
          terraform -chdir=azure/terraform/app init \
            -var-file=../../conf/${{ parameters.environment }}/env.tfvars \
            -backend-config=../../conf/${{ parameters.environment }}/backend-app.tfvars -input=false
    - task: CmdLine@2
      displayName: TF Validate
      inputs:
        script: |
          terraform -chdir=azure/terraform/app validate
    - ${{ if eq(parameters.action, 'destroy') }}:
      - task: AzureCLI@2
        displayName: TF Destroy
        condition: eq(${{ parameters.dryRun }}, false)
        inputs:
          azureSubscription: ${{ variables.SERVICE_CONNECTION }}
          addSpnToEnvironment: true
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            terraform -chdir=azure/terraform/app destroy \
              -var-file=../../conf/${{ parameters.environment }}/env.tfvars \
              -input=false -auto-approve
    - ${{ else }}:
      - task: AzureCLI@2
        displayName: TF Plan
        inputs:
          azureSubscription: ${{ variables.SERVICE_CONNECTION }}
          addSpnToEnvironment: true
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            terraform -chdir=azure/terraform/app plan -input=false -detailed-exitcode \
              -var-file=../../conf/${{ parameters.environment }}/env.tfvars \
              -out=app.tfplan -lock-timeout=1m
            exit_code=$?
            echo "INFO: exit_code: $exit_code"
            if [[ $exit_code -eq 0 ]]; then
              echo "INFO: terrafrom plan has no changes"
              echo "##vso[task.setvariable variable=TERRAFORM_PLAN_HAS_CHANGES;]false"
            elif [[ $exit_code -eq 2 ]]; then
              echo "INFO: Terrafrom plan has changes"
              echo "##vso[task.setvariable variable=TERRAFORM_PLAN_HAS_CHANGES;]true"
            else
              echo "ERROR: Terraform error"
              exit $exit_code
            fi
      - task: AzureCLI@2
        displayName: TF Apply
        condition: and(succeeded(), eq(${{ parameters.dryRun }}, false))
        inputs:
          azureSubscription: ${{ variables.SERVICE_CONNECTION }}
          addSpnToEnvironment: true
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            if [ "$TERRAFORM_PLAN_HAS_CHANGES" = true ]; then
              terraform -chdir=azure/terraform/app apply app.tfplan
            else
              echo "No changes were discovered"
            fi