# Pipeline to build container images for the app services and publish them to ACR.
parameters:
  - name: env
    displayName: Environment to manage
    type: string
    default: dev
    values:
    - dev
    - all
  - name: cleanup
    type: boolean
    default: false

variables:
- template: ../conf/${{ parameters.env }}/env.yaml
- name: imgtag
  value: '$(Build.BuildId)'
- name: majorVersion
  value: '1.0'

stages:

# Build the app container
- stage: Build
  displayName: Build containers images
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: CmdLine@2
      displayName: Show environment
      inputs:
        script: |
          env | sort
    - task: AzureCLI@2
      displayName: "Enable az extensions autoinstall"
      inputs:
        azureSubscription: $(SERVICE_CONNECTION)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az config set extension.use_dynamic_install=yes_without_prompt
    - task: AzureCLI@2
      displayName: "Set ACR credentials for the account"
      inputs:
        azureSubscription: $(SERVICE_CONNECTION)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az acr login -n $(ACR_NAME)
          ACRUSER=$(az acr credential show --name $(ACR_NAME)  --query "username")
          echo "##vso[task.setvariable variable=ACRUSER;]$ACRUSER"
          ACRPASS=$(az acr credential show --name $(ACR_NAME) --query "passwords[0].value")
          echo "##vso[task.setvariable variable=ACRPASS;]$ACRPASS"
    - task: AzureCLI@2
      displayName: "Build and publish node-frontend container image"
      inputs:
        azureSubscription: $(SERVICE_CONNECTION)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az acr build --registry $(ACR_NAME) --image node-frontend:$(majorVersion).$BUILD_BUILDID ./node-frontend
          az acr repository untag -n $(ACR_NAME) -t node-frontend:latest
          az acr import \
            --name $(ACR_NAME) \
            --source $(ACR_NAME)/node-frontend:$(majorVersion).$BUILD_BUILDID \
            --image node-frontend:latest
    - task: AzureCLI@2
      displayName: "Build and publish python-service-gateway container image"
      inputs:
        azureSubscription: $(SERVICE_CONNECTION)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az acr build --registry $(ACR_NAME) --image python-service-gateway:$(majorVersion).$BUILD_BUILDID ./python-service-gateway
          az acr repository untag -n $(ACR_NAME) -t python-service-gateway:latest
          az acr import \
            --name $(ACR_NAME) \
            --source $(ACR_NAME)/python-service-gateway:$(majorVersion).$BUILD_BUILDID \
            --image python-service-gateway:latest
    - task: AzureCLI@2
      displayName: "Build and publish node-service-blue container image"
      inputs:
        azureSubscription: $(SERVICE_CONNECTION)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az acr build --registry $(ACR_NAME) --image node-service-blue:$(majorVersion).$BUILD_BUILDID ./node-service-blue
          az acr repository untag -n $(ACR_NAME) -t node-service-blue:latest
          az acr import \
            --name $(ACR_NAME) \
            --source $(ACR_NAME)/node-service-blue:$(majorVersion).$BUILD_BUILDID \
            --image node-service-blue:latest
    - task: AzureCLI@2
      displayName: "Build and publish python-service-green container image"
      inputs:
        azureSubscription: $(SERVICE_CONNECTION)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az acr build --registry $(ACR_NAME) --image python-service-green:$(majorVersion).$BUILD_BUILDID ./python-service-green
          az acr repository untag -n $(ACR_NAME) -t python-service-green:latest
          az acr import \
            --name $(ACR_NAME) \
            --source $(ACR_NAME)/python-service-green:$(majorVersion).$BUILD_BUILDID \
            --image python-service-green:latest